app = "bfaas"
[[restart]]
    policy = "always"
    restries = 0
    processes = ["app"]
   
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 1
    hard_limit = 1